# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /run/media/atharva/nux/ece540_rvfpga_sources/Labs/Proj_3_VGA_Lab/project_3_VGA/project_3_VGA.srcs/sources_1/ip/blk_mem_vga/blk_mem_vga.xci
# IP: The module: 'blk_mem_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /run/media/atharva/nux/ece540_rvfpga_sources/Labs/Proj_3_VGA_Lab/project_3_VGA/project_3_VGA.srcs/sources_1/ip/blk_mem_vga/blk_mem_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_vga'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /run/media/atharva/nux/ece540_rvfpga_sources/Labs/Proj_3_VGA_Lab/project_3_VGA/project_3_VGA.srcs/sources_1/ip/blk_mem_vga/blk_mem_vga.xci
# IP: The module: 'blk_mem_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /run/media/atharva/nux/ece540_rvfpga_sources/Labs/Proj_3_VGA_Lab/project_3_VGA/project_3_VGA.srcs/sources_1/ip/blk_mem_vga/blk_mem_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
